### ISSUE TITLE
compilation error on Ubuntu22

### ISSUE THREAD

**Issue by ferdymercury** [martukas/nuclei#6]
When I try to compile the software (master branch), I get:
```
ERROR: Package 'Qt-Color-Widgets/9f4e052@ess-dmsc/stable' not resolved: Qt-Color-Widgets/9f4e052@ess-dmsc/stable: Cannot load recipe.
Error loading conanfile at '/home/user/.conan2/p/Qt-Co32bc14517ff1e/e/conanfile.py': Unable to load conanfile in /home/user/.conan2/p/Qt-Co32bc14517ff1e/e/conanfile.py
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/user/.conan2/p/Qt-Co32bc14517ff1e/e/conanfile.py", line 2, in <module>
    from conans import ConanFile, CMake, tools
ImportError: cannot import name 'ConanFile' from 'conans' (/usr/local/lib/python3.10/dist-packages/conans/__init__.py)
.
CMake Error at build/conan.cmake:540 (message):
  Conan install failed='1'
Call Stack (most recent call first):
  build/conan.cmake:882 (old_conan_cmake_install)
  CMakeLists.txt:32 (conan_cmake_run)
```

**Comment by ferdymercury** [comment]
If I change to non-capitalized package in the conanfile, I get:

```
ERROR: Missing prebuilt package for 'qt-color-widgets/9f4e052@ess-dmsc/stable'
Check the available packages using 'conan list qt-color-widgets/9f4e052@ess-dmsc/stable:* -r=remote'
or try to build locally from sources using the '--build=qt-color-widgets/9f4e052@ess-dmsc/stable' argument

More Info at 'https://docs.conan.io/2/knowledge/faq.html#error-missing-prebuilt-package'

CMake Error at build/conan.cmake:540 (message):
  Conan install failed='1'
Call Stack (most recent call first):
  build/conan.cmake:882 (old_conan_cmake_install)
  CMakeLists.txt:32 (conan_cmake_run)

```

**Comment by ferdymercury** [comment]
For this we maybe need: https://github.com/conan-io/cmake-conan/tree/develop2

**Comment by ferdymercury** [comment]
Otherwise, we should state that conan 1.52 is needed or sth like that rather than 2

It seems to work with conan 1.60 on Ubuntu 22, and installing libqt5svg5-dev

**Comment by php1ic** [comment]
This may have been me, creating a PR to get the Qt-Color-Widgets repo working with conan v2 now that that is the default version with `pip install conan`

https://github.com/ess-dmsc/conan-Qt-Color-Widgets/pull/6

Ironically, the PR was to try and get this project compiled on my computer  :facepalm: 

I'm still learning about conan, but I'm not sure you can mix and match 1.X and 2.X versions. I have a branch that is updating this repo to use conan v2 and will push once I get it compiling. I'm running on fedora38 with gcc13 and am currently getting compilation errors.

**Comment by martukas** [comment]
I would say let's switch to conan2 if that is the future, and not look back. Same for any libraries, compilers, dependencies. Latest Ubuntu LTS and don't bother with backwards compatibility.

**Comment by martukas** [comment]
@php1ic I think there is still a problem with the Conan package for `QtColorWidgets`. You may have reconfigured it for conan2 and it probably builds correctly for you locally, but it is not successfully deploying to the ESS-DMSC repositories that have kindly agreed to host it. I suspect the problem is a common one where you changed the package, but did not update the package version name. Since it tags the same commit hash as the old one, it's not differentiated. You either needed to append something like `-v2` to the end of it, or, better yet, just reference the latest commit of the referenced repo, which is no longer what it was. Does this make sense?

@ferdymercury yes, for now we could just document that it needs an older conan version. At the time I worked on this, there was not yet any divergence in conan to worry about so there was no need to document this. But I think now it's maybe better to just migrate to conan2 instead?

**Comment by martukas** [comment]
The latest commit of `QtColorWidgets` (not its conan package recipe!) is `f72207b` as you can see here:
https://github.com/ess-dmsc/Qt-Color-Widgets/commits/master

Which is probably what the new conan2 package should be named after.

**Comment by php1ic** [comment]
Agreed, if there are new versions of the `QtColorWidgets` package, this project should use those. However, I don't believe pointing to an older version of that repo is the issue, I think it's that conan2 now requires packages to be all lowercase (https://docs.conan.io/2/tutorial/creating_packages/create_your_first_package.html), `QtColorWidgets` has made that change but this repo hasn't updated the conanfile.txt. 

My work in progress branch for all necessary changed for conan2 is part of #16. See the comment on the PR, everything looks to configure correctly, but I can see that the nlohmann package is not added to the includes path so compilation fails.

**Comment by ferdymercury** [comment]
The linked PR fixes all problems with Ubuntu 22. @martukas can you take a look and merge it if it also works on your side?
